// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emrsystem.proxies;

public class Biochemistry
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject biochemistryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EMRSystem.Biochemistry";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TestID("TestID"),
		PersonRecorded("PersonRecorded"),
		RoleOfPerson("RoleOfPerson"),
		OrganizationName("OrganizationName"),
		OrganizationID("OrganizationID"),
		SnomedCode("SnomedCode"),
		TimeRecorded("TimeRecorded"),
		RecordElementIdentifier("RecordElementIdentifier"),
		SourceSystemIdentity("SourceSystemIdentity"),
		ExtractIdentifier("ExtractIdentifier"),
		ExtractTime("ExtractTime"),
		Biochemistry_Investigation("EMRSystem.Biochemistry_Investigation");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Biochemistry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EMRSystem.Biochemistry"));
	}

	protected Biochemistry(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject biochemistryMendixObject)
	{
		if (biochemistryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EMRSystem.Biochemistry", biochemistryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EMRSystem.Biochemistry");

		this.biochemistryMendixObject = biochemistryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Biochemistry.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static emrsystem.proxies.Biochemistry initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emrsystem.proxies.Biochemistry.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emrsystem.proxies.Biochemistry initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emrsystem.proxies.Biochemistry(context, mendixObject);
	}

	public static emrsystem.proxies.Biochemistry load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emrsystem.proxies.Biochemistry.initialize(context, mendixObject);
	}

	public static java.util.List<emrsystem.proxies.Biochemistry> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emrsystem.proxies.Biochemistry> result = new java.util.ArrayList<emrsystem.proxies.Biochemistry>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EMRSystem.Biochemistry" + xpathConstraint))
			result.add(emrsystem.proxies.Biochemistry.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TestID
	 */
	public final java.lang.String getTestID()
	{
		return getTestID(getContext());
	}

	/**
	 * @param context
	 * @return value of TestID
	 */
	public final java.lang.String getTestID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TestID.toString());
	}

	/**
	 * Set value of TestID
	 * @param testid
	 */
	public final void setTestID(java.lang.String testid)
	{
		setTestID(getContext(), testid);
	}

	/**
	 * Set value of TestID
	 * @param context
	 * @param testid
	 */
	public final void setTestID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String testid)
	{
		getMendixObject().setValue(context, MemberNames.TestID.toString(), testid);
	}

	/**
	 * @return value of PersonRecorded
	 */
	public final java.lang.String getPersonRecorded()
	{
		return getPersonRecorded(getContext());
	}

	/**
	 * @param context
	 * @return value of PersonRecorded
	 */
	public final java.lang.String getPersonRecorded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PersonRecorded.toString());
	}

	/**
	 * Set value of PersonRecorded
	 * @param personrecorded
	 */
	public final void setPersonRecorded(java.lang.String personrecorded)
	{
		setPersonRecorded(getContext(), personrecorded);
	}

	/**
	 * Set value of PersonRecorded
	 * @param context
	 * @param personrecorded
	 */
	public final void setPersonRecorded(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String personrecorded)
	{
		getMendixObject().setValue(context, MemberNames.PersonRecorded.toString(), personrecorded);
	}

	/**
	 * @return value of RoleOfPerson
	 */
	public final java.lang.String getRoleOfPerson()
	{
		return getRoleOfPerson(getContext());
	}

	/**
	 * @param context
	 * @return value of RoleOfPerson
	 */
	public final java.lang.String getRoleOfPerson(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RoleOfPerson.toString());
	}

	/**
	 * Set value of RoleOfPerson
	 * @param roleofperson
	 */
	public final void setRoleOfPerson(java.lang.String roleofperson)
	{
		setRoleOfPerson(getContext(), roleofperson);
	}

	/**
	 * Set value of RoleOfPerson
	 * @param context
	 * @param roleofperson
	 */
	public final void setRoleOfPerson(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String roleofperson)
	{
		getMendixObject().setValue(context, MemberNames.RoleOfPerson.toString(), roleofperson);
	}

	/**
	 * @return value of OrganizationName
	 */
	public final java.lang.String getOrganizationName()
	{
		return getOrganizationName(getContext());
	}

	/**
	 * @param context
	 * @return value of OrganizationName
	 */
	public final java.lang.String getOrganizationName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrganizationName.toString());
	}

	/**
	 * Set value of OrganizationName
	 * @param organizationname
	 */
	public final void setOrganizationName(java.lang.String organizationname)
	{
		setOrganizationName(getContext(), organizationname);
	}

	/**
	 * Set value of OrganizationName
	 * @param context
	 * @param organizationname
	 */
	public final void setOrganizationName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String organizationname)
	{
		getMendixObject().setValue(context, MemberNames.OrganizationName.toString(), organizationname);
	}

	/**
	 * @return value of OrganizationID
	 */
	public final java.lang.String getOrganizationID()
	{
		return getOrganizationID(getContext());
	}

	/**
	 * @param context
	 * @return value of OrganizationID
	 */
	public final java.lang.String getOrganizationID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrganizationID.toString());
	}

	/**
	 * Set value of OrganizationID
	 * @param organizationid
	 */
	public final void setOrganizationID(java.lang.String organizationid)
	{
		setOrganizationID(getContext(), organizationid);
	}

	/**
	 * Set value of OrganizationID
	 * @param context
	 * @param organizationid
	 */
	public final void setOrganizationID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String organizationid)
	{
		getMendixObject().setValue(context, MemberNames.OrganizationID.toString(), organizationid);
	}

	/**
	 * @return value of SnomedCode
	 */
	public final java.lang.String getSnomedCode()
	{
		return getSnomedCode(getContext());
	}

	/**
	 * @param context
	 * @return value of SnomedCode
	 */
	public final java.lang.String getSnomedCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SnomedCode.toString());
	}

	/**
	 * Set value of SnomedCode
	 * @param snomedcode
	 */
	public final void setSnomedCode(java.lang.String snomedcode)
	{
		setSnomedCode(getContext(), snomedcode);
	}

	/**
	 * Set value of SnomedCode
	 * @param context
	 * @param snomedcode
	 */
	public final void setSnomedCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String snomedcode)
	{
		getMendixObject().setValue(context, MemberNames.SnomedCode.toString(), snomedcode);
	}

	/**
	 * @return value of TimeRecorded
	 */
	public final java.util.Date getTimeRecorded()
	{
		return getTimeRecorded(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeRecorded
	 */
	public final java.util.Date getTimeRecorded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TimeRecorded.toString());
	}

	/**
	 * Set value of TimeRecorded
	 * @param timerecorded
	 */
	public final void setTimeRecorded(java.util.Date timerecorded)
	{
		setTimeRecorded(getContext(), timerecorded);
	}

	/**
	 * Set value of TimeRecorded
	 * @param context
	 * @param timerecorded
	 */
	public final void setTimeRecorded(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timerecorded)
	{
		getMendixObject().setValue(context, MemberNames.TimeRecorded.toString(), timerecorded);
	}

	/**
	 * @return value of RecordElementIdentifier
	 */
	public final java.lang.String getRecordElementIdentifier()
	{
		return getRecordElementIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of RecordElementIdentifier
	 */
	public final java.lang.String getRecordElementIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RecordElementIdentifier.toString());
	}

	/**
	 * Set value of RecordElementIdentifier
	 * @param recordelementidentifier
	 */
	public final void setRecordElementIdentifier(java.lang.String recordelementidentifier)
	{
		setRecordElementIdentifier(getContext(), recordelementidentifier);
	}

	/**
	 * Set value of RecordElementIdentifier
	 * @param context
	 * @param recordelementidentifier
	 */
	public final void setRecordElementIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recordelementidentifier)
	{
		getMendixObject().setValue(context, MemberNames.RecordElementIdentifier.toString(), recordelementidentifier);
	}

	/**
	 * @return value of SourceSystemIdentity
	 */
	public final java.lang.String getSourceSystemIdentity()
	{
		return getSourceSystemIdentity(getContext());
	}

	/**
	 * @param context
	 * @return value of SourceSystemIdentity
	 */
	public final java.lang.String getSourceSystemIdentity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SourceSystemIdentity.toString());
	}

	/**
	 * Set value of SourceSystemIdentity
	 * @param sourcesystemidentity
	 */
	public final void setSourceSystemIdentity(java.lang.String sourcesystemidentity)
	{
		setSourceSystemIdentity(getContext(), sourcesystemidentity);
	}

	/**
	 * Set value of SourceSystemIdentity
	 * @param context
	 * @param sourcesystemidentity
	 */
	public final void setSourceSystemIdentity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sourcesystemidentity)
	{
		getMendixObject().setValue(context, MemberNames.SourceSystemIdentity.toString(), sourcesystemidentity);
	}

	/**
	 * @return value of ExtractIdentifier
	 */
	public final java.lang.String getExtractIdentifier()
	{
		return getExtractIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of ExtractIdentifier
	 */
	public final java.lang.String getExtractIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExtractIdentifier.toString());
	}

	/**
	 * Set value of ExtractIdentifier
	 * @param extractidentifier
	 */
	public final void setExtractIdentifier(java.lang.String extractidentifier)
	{
		setExtractIdentifier(getContext(), extractidentifier);
	}

	/**
	 * Set value of ExtractIdentifier
	 * @param context
	 * @param extractidentifier
	 */
	public final void setExtractIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String extractidentifier)
	{
		getMendixObject().setValue(context, MemberNames.ExtractIdentifier.toString(), extractidentifier);
	}

	/**
	 * @return value of ExtractTime
	 */
	public final java.lang.String getExtractTime()
	{
		return getExtractTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ExtractTime
	 */
	public final java.lang.String getExtractTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExtractTime.toString());
	}

	/**
	 * Set value of ExtractTime
	 * @param extracttime
	 */
	public final void setExtractTime(java.lang.String extracttime)
	{
		setExtractTime(getContext(), extracttime);
	}

	/**
	 * Set value of ExtractTime
	 * @param context
	 * @param extracttime
	 */
	public final void setExtractTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String extracttime)
	{
		getMendixObject().setValue(context, MemberNames.ExtractTime.toString(), extracttime);
	}

	/**
	 * @return value of Biochemistry_Investigation
	 */
	public final emrsystem.proxies.RecentTests getBiochemistry_Investigation() throws com.mendix.core.CoreException
	{
		return getBiochemistry_Investigation(getContext());
	}

	/**
	 * @param context
	 * @return value of Biochemistry_Investigation
	 */
	public final emrsystem.proxies.RecentTests getBiochemistry_Investigation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emrsystem.proxies.RecentTests result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Biochemistry_Investigation.toString());
		if (identifier != null)
			result = emrsystem.proxies.RecentTests.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Biochemistry_Investigation
	 * @param biochemistry_investigation
	 */
	public final void setBiochemistry_Investigation(emrsystem.proxies.RecentTests biochemistry_investigation)
	{
		setBiochemistry_Investigation(getContext(), biochemistry_investigation);
	}

	/**
	 * Set value of Biochemistry_Investigation
	 * @param context
	 * @param biochemistry_investigation
	 */
	public final void setBiochemistry_Investigation(com.mendix.systemwideinterfaces.core.IContext context, emrsystem.proxies.RecentTests biochemistry_investigation)
	{
		if (biochemistry_investigation == null)
			getMendixObject().setValue(context, MemberNames.Biochemistry_Investigation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Biochemistry_Investigation.toString(), biochemistry_investigation.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return biochemistryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emrsystem.proxies.Biochemistry that = (emrsystem.proxies.Biochemistry) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EMRSystem.Biochemistry";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
