// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emrsystem.proxies;

public class CurrentMedication
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject currentMedicationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EMRSystem.CurrentMedication";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PatientIC("PatientIC"),
		MedicationID("MedicationID"),
		MedicationName("MedicationName"),
		MedicationDescription("MedicationDescription"),
		IsAcuteMedication("IsAcuteMedication"),
		IsRepeatMedication("IsRepeatMedication"),
		Medication_Patient("EMRSystem.Medication_Patient"),
		RiskAndWarning_Medication("EMRSystem.RiskAndWarning_Medication");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CurrentMedication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EMRSystem.CurrentMedication"));
	}

	protected CurrentMedication(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject currentMedicationMendixObject)
	{
		if (currentMedicationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EMRSystem.CurrentMedication", currentMedicationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EMRSystem.CurrentMedication");

		this.currentMedicationMendixObject = currentMedicationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CurrentMedication.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static emrsystem.proxies.CurrentMedication initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emrsystem.proxies.CurrentMedication.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emrsystem.proxies.CurrentMedication initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emrsystem.proxies.CurrentMedication(context, mendixObject);
	}

	public static emrsystem.proxies.CurrentMedication load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emrsystem.proxies.CurrentMedication.initialize(context, mendixObject);
	}

	public static java.util.List<emrsystem.proxies.CurrentMedication> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emrsystem.proxies.CurrentMedication> result = new java.util.ArrayList<emrsystem.proxies.CurrentMedication>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EMRSystem.CurrentMedication" + xpathConstraint))
			result.add(emrsystem.proxies.CurrentMedication.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of PatientIC
	 */
	public final java.lang.String getPatientIC()
	{
		return getPatientIC(getContext());
	}

	/**
	 * @param context
	 * @return value of PatientIC
	 */
	public final java.lang.String getPatientIC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PatientIC.toString());
	}

	/**
	 * Set value of PatientIC
	 * @param patientic
	 */
	public final void setPatientIC(java.lang.String patientic)
	{
		setPatientIC(getContext(), patientic);
	}

	/**
	 * Set value of PatientIC
	 * @param context
	 * @param patientic
	 */
	public final void setPatientIC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String patientic)
	{
		getMendixObject().setValue(context, MemberNames.PatientIC.toString(), patientic);
	}

	/**
	 * @return value of MedicationID
	 */
	public final java.lang.String getMedicationID()
	{
		return getMedicationID(getContext());
	}

	/**
	 * @param context
	 * @return value of MedicationID
	 */
	public final java.lang.String getMedicationID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MedicationID.toString());
	}

	/**
	 * Set value of MedicationID
	 * @param medicationid
	 */
	public final void setMedicationID(java.lang.String medicationid)
	{
		setMedicationID(getContext(), medicationid);
	}

	/**
	 * Set value of MedicationID
	 * @param context
	 * @param medicationid
	 */
	public final void setMedicationID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String medicationid)
	{
		getMendixObject().setValue(context, MemberNames.MedicationID.toString(), medicationid);
	}

	/**
	 * @return value of MedicationName
	 */
	public final java.lang.String getMedicationName()
	{
		return getMedicationName(getContext());
	}

	/**
	 * @param context
	 * @return value of MedicationName
	 */
	public final java.lang.String getMedicationName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MedicationName.toString());
	}

	/**
	 * Set value of MedicationName
	 * @param medicationname
	 */
	public final void setMedicationName(java.lang.String medicationname)
	{
		setMedicationName(getContext(), medicationname);
	}

	/**
	 * Set value of MedicationName
	 * @param context
	 * @param medicationname
	 */
	public final void setMedicationName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String medicationname)
	{
		getMendixObject().setValue(context, MemberNames.MedicationName.toString(), medicationname);
	}

	/**
	 * @return value of MedicationDescription
	 */
	public final java.lang.String getMedicationDescription()
	{
		return getMedicationDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of MedicationDescription
	 */
	public final java.lang.String getMedicationDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MedicationDescription.toString());
	}

	/**
	 * Set value of MedicationDescription
	 * @param medicationdescription
	 */
	public final void setMedicationDescription(java.lang.String medicationdescription)
	{
		setMedicationDescription(getContext(), medicationdescription);
	}

	/**
	 * Set value of MedicationDescription
	 * @param context
	 * @param medicationdescription
	 */
	public final void setMedicationDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String medicationdescription)
	{
		getMendixObject().setValue(context, MemberNames.MedicationDescription.toString(), medicationdescription);
	}

	/**
	 * @return value of IsAcuteMedication
	 */
	public final java.lang.Boolean getIsAcuteMedication()
	{
		return getIsAcuteMedication(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAcuteMedication
	 */
	public final java.lang.Boolean getIsAcuteMedication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAcuteMedication.toString());
	}

	/**
	 * Set value of IsAcuteMedication
	 * @param isacutemedication
	 */
	public final void setIsAcuteMedication(java.lang.Boolean isacutemedication)
	{
		setIsAcuteMedication(getContext(), isacutemedication);
	}

	/**
	 * Set value of IsAcuteMedication
	 * @param context
	 * @param isacutemedication
	 */
	public final void setIsAcuteMedication(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isacutemedication)
	{
		getMendixObject().setValue(context, MemberNames.IsAcuteMedication.toString(), isacutemedication);
	}

	/**
	 * @return value of IsRepeatMedication
	 */
	public final java.lang.Boolean getIsRepeatMedication()
	{
		return getIsRepeatMedication(getContext());
	}

	/**
	 * @param context
	 * @return value of IsRepeatMedication
	 */
	public final java.lang.Boolean getIsRepeatMedication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsRepeatMedication.toString());
	}

	/**
	 * Set value of IsRepeatMedication
	 * @param isrepeatmedication
	 */
	public final void setIsRepeatMedication(java.lang.Boolean isrepeatmedication)
	{
		setIsRepeatMedication(getContext(), isrepeatmedication);
	}

	/**
	 * Set value of IsRepeatMedication
	 * @param context
	 * @param isrepeatmedication
	 */
	public final void setIsRepeatMedication(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isrepeatmedication)
	{
		getMendixObject().setValue(context, MemberNames.IsRepeatMedication.toString(), isrepeatmedication);
	}

	/**
	 * @return value of Medication_Patient
	 */
	public final emrsystem.proxies.PatientDetails getMedication_Patient() throws com.mendix.core.CoreException
	{
		return getMedication_Patient(getContext());
	}

	/**
	 * @param context
	 * @return value of Medication_Patient
	 */
	public final emrsystem.proxies.PatientDetails getMedication_Patient(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emrsystem.proxies.PatientDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Medication_Patient.toString());
		if (identifier != null)
			result = emrsystem.proxies.PatientDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Medication_Patient
	 * @param medication_patient
	 */
	public final void setMedication_Patient(emrsystem.proxies.PatientDetails medication_patient)
	{
		setMedication_Patient(getContext(), medication_patient);
	}

	/**
	 * Set value of Medication_Patient
	 * @param context
	 * @param medication_patient
	 */
	public final void setMedication_Patient(com.mendix.systemwideinterfaces.core.IContext context, emrsystem.proxies.PatientDetails medication_patient)
	{
		if (medication_patient == null)
			getMendixObject().setValue(context, MemberNames.Medication_Patient.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Medication_Patient.toString(), medication_patient.getMendixObject().getId());
	}

	/**
	 * @return value of RiskAndWarning_Medication
	 */
	public final emrsystem.proxies.RiskAndWarning getRiskAndWarning_Medication() throws com.mendix.core.CoreException
	{
		return getRiskAndWarning_Medication(getContext());
	}

	/**
	 * @param context
	 * @return value of RiskAndWarning_Medication
	 */
	public final emrsystem.proxies.RiskAndWarning getRiskAndWarning_Medication(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emrsystem.proxies.RiskAndWarning result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RiskAndWarning_Medication.toString());
		if (identifier != null)
			result = emrsystem.proxies.RiskAndWarning.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RiskAndWarning_Medication
	 * @param riskandwarning_medication
	 */
	public final void setRiskAndWarning_Medication(emrsystem.proxies.RiskAndWarning riskandwarning_medication)
	{
		setRiskAndWarning_Medication(getContext(), riskandwarning_medication);
	}

	/**
	 * Set value of RiskAndWarning_Medication
	 * @param context
	 * @param riskandwarning_medication
	 */
	public final void setRiskAndWarning_Medication(com.mendix.systemwideinterfaces.core.IContext context, emrsystem.proxies.RiskAndWarning riskandwarning_medication)
	{
		if (riskandwarning_medication == null)
			getMendixObject().setValue(context, MemberNames.RiskAndWarning_Medication.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RiskAndWarning_Medication.toString(), riskandwarning_medication.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return currentMedicationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emrsystem.proxies.CurrentMedication that = (emrsystem.proxies.CurrentMedication) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EMRSystem.CurrentMedication";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
