// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emrsystem.proxies;

public class Examination
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject examinationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EMRSystem.Examination";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ProcedureID("ProcedureID"),
		TreatmentResultDescription("TreatmentResultDescription"),
		AbleToLeaveHospital("AbleToLeaveHospital"),
		TreatmentAmountToCharge("TreatmentAmountToCharge"),
		Examination_Procedures("EMRSystem.Examination_Procedures");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Examination(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EMRSystem.Examination"));
	}

	protected Examination(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject examinationMendixObject)
	{
		if (examinationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EMRSystem.Examination", examinationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EMRSystem.Examination");

		this.examinationMendixObject = examinationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Examination.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static emrsystem.proxies.Examination initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emrsystem.proxies.Examination.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emrsystem.proxies.Examination initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emrsystem.proxies.Examination(context, mendixObject);
	}

	public static emrsystem.proxies.Examination load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emrsystem.proxies.Examination.initialize(context, mendixObject);
	}

	public static java.util.List<emrsystem.proxies.Examination> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emrsystem.proxies.Examination> result = new java.util.ArrayList<emrsystem.proxies.Examination>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EMRSystem.Examination" + xpathConstraint))
			result.add(emrsystem.proxies.Examination.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ProcedureID
	 */
	public final java.lang.String getProcedureID()
	{
		return getProcedureID(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcedureID
	 */
	public final java.lang.String getProcedureID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProcedureID.toString());
	}

	/**
	 * Set value of ProcedureID
	 * @param procedureid
	 */
	public final void setProcedureID(java.lang.String procedureid)
	{
		setProcedureID(getContext(), procedureid);
	}

	/**
	 * Set value of ProcedureID
	 * @param context
	 * @param procedureid
	 */
	public final void setProcedureID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String procedureid)
	{
		getMendixObject().setValue(context, MemberNames.ProcedureID.toString(), procedureid);
	}

	/**
	 * @return value of TreatmentResultDescription
	 */
	public final java.lang.String getTreatmentResultDescription()
	{
		return getTreatmentResultDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of TreatmentResultDescription
	 */
	public final java.lang.String getTreatmentResultDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TreatmentResultDescription.toString());
	}

	/**
	 * Set value of TreatmentResultDescription
	 * @param treatmentresultdescription
	 */
	public final void setTreatmentResultDescription(java.lang.String treatmentresultdescription)
	{
		setTreatmentResultDescription(getContext(), treatmentresultdescription);
	}

	/**
	 * Set value of TreatmentResultDescription
	 * @param context
	 * @param treatmentresultdescription
	 */
	public final void setTreatmentResultDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String treatmentresultdescription)
	{
		getMendixObject().setValue(context, MemberNames.TreatmentResultDescription.toString(), treatmentresultdescription);
	}

	/**
	 * @return value of AbleToLeaveHospital
	 */
	public final java.lang.Boolean getAbleToLeaveHospital()
	{
		return getAbleToLeaveHospital(getContext());
	}

	/**
	 * @param context
	 * @return value of AbleToLeaveHospital
	 */
	public final java.lang.Boolean getAbleToLeaveHospital(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AbleToLeaveHospital.toString());
	}

	/**
	 * Set value of AbleToLeaveHospital
	 * @param abletoleavehospital
	 */
	public final void setAbleToLeaveHospital(java.lang.Boolean abletoleavehospital)
	{
		setAbleToLeaveHospital(getContext(), abletoleavehospital);
	}

	/**
	 * Set value of AbleToLeaveHospital
	 * @param context
	 * @param abletoleavehospital
	 */
	public final void setAbleToLeaveHospital(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean abletoleavehospital)
	{
		getMendixObject().setValue(context, MemberNames.AbleToLeaveHospital.toString(), abletoleavehospital);
	}

	/**
	 * @return value of TreatmentAmountToCharge
	 */
	public final java.lang.Double getTreatmentAmountToCharge()
	{
		return getTreatmentAmountToCharge(getContext());
	}

	/**
	 * @param context
	 * @return value of TreatmentAmountToCharge
	 */
	public final java.lang.Double getTreatmentAmountToCharge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.TreatmentAmountToCharge.toString());
	}

	/**
	 * Set value of TreatmentAmountToCharge
	 * @param treatmentamounttocharge
	 */
	public final void setTreatmentAmountToCharge(java.lang.Double treatmentamounttocharge)
	{
		setTreatmentAmountToCharge(getContext(), treatmentamounttocharge);
	}

	/**
	 * Set value of TreatmentAmountToCharge
	 * @param context
	 * @param treatmentamounttocharge
	 */
	public final void setTreatmentAmountToCharge(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double treatmentamounttocharge)
	{
		getMendixObject().setValue(context, MemberNames.TreatmentAmountToCharge.toString(), treatmentamounttocharge);
	}

	/**
	 * @return value of Examination_Procedures
	 */
	public final emrsystem.proxies.Procedures getExamination_Procedures() throws com.mendix.core.CoreException
	{
		return getExamination_Procedures(getContext());
	}

	/**
	 * @param context
	 * @return value of Examination_Procedures
	 */
	public final emrsystem.proxies.Procedures getExamination_Procedures(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emrsystem.proxies.Procedures result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Examination_Procedures.toString());
		if (identifier != null)
			result = emrsystem.proxies.Procedures.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Examination_Procedures
	 * @param examination_procedures
	 */
	public final void setExamination_Procedures(emrsystem.proxies.Procedures examination_procedures)
	{
		setExamination_Procedures(getContext(), examination_procedures);
	}

	/**
	 * Set value of Examination_Procedures
	 * @param context
	 * @param examination_procedures
	 */
	public final void setExamination_Procedures(com.mendix.systemwideinterfaces.core.IContext context, emrsystem.proxies.Procedures examination_procedures)
	{
		if (examination_procedures == null)
			getMendixObject().setValue(context, MemberNames.Examination_Procedures.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Examination_Procedures.toString(), examination_procedures.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return examinationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emrsystem.proxies.Examination that = (emrsystem.proxies.Examination) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EMRSystem.Examination";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
