// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emrsystem.proxies;

public class Referrals
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject referralsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EMRSystem.Referrals";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TestID("TestID"),
		DateOfRefer("DateOfRefer"),
		Encounter("Encounter"),
		UserOrRole("UserOrRole"),
		Where("Where"),
		ByWhom("ByWhom"),
		Reason("Reason"),
		Referrals_RecentTests("EMRSystem.Referrals_RecentTests");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Referrals(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EMRSystem.Referrals"));
	}

	protected Referrals(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject referralsMendixObject)
	{
		if (referralsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EMRSystem.Referrals", referralsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EMRSystem.Referrals");

		this.referralsMendixObject = referralsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Referrals.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static emrsystem.proxies.Referrals initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emrsystem.proxies.Referrals.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emrsystem.proxies.Referrals initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emrsystem.proxies.Referrals(context, mendixObject);
	}

	public static emrsystem.proxies.Referrals load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emrsystem.proxies.Referrals.initialize(context, mendixObject);
	}

	public static java.util.List<emrsystem.proxies.Referrals> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emrsystem.proxies.Referrals> result = new java.util.ArrayList<emrsystem.proxies.Referrals>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EMRSystem.Referrals" + xpathConstraint))
			result.add(emrsystem.proxies.Referrals.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TestID
	 */
	public final java.lang.String getTestID()
	{
		return getTestID(getContext());
	}

	/**
	 * @param context
	 * @return value of TestID
	 */
	public final java.lang.String getTestID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TestID.toString());
	}

	/**
	 * Set value of TestID
	 * @param testid
	 */
	public final void setTestID(java.lang.String testid)
	{
		setTestID(getContext(), testid);
	}

	/**
	 * Set value of TestID
	 * @param context
	 * @param testid
	 */
	public final void setTestID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String testid)
	{
		getMendixObject().setValue(context, MemberNames.TestID.toString(), testid);
	}

	/**
	 * @return value of DateOfRefer
	 */
	public final java.util.Date getDateOfRefer()
	{
		return getDateOfRefer(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfRefer
	 */
	public final java.util.Date getDateOfRefer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfRefer.toString());
	}

	/**
	 * Set value of DateOfRefer
	 * @param dateofrefer
	 */
	public final void setDateOfRefer(java.util.Date dateofrefer)
	{
		setDateOfRefer(getContext(), dateofrefer);
	}

	/**
	 * Set value of DateOfRefer
	 * @param context
	 * @param dateofrefer
	 */
	public final void setDateOfRefer(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofrefer)
	{
		getMendixObject().setValue(context, MemberNames.DateOfRefer.toString(), dateofrefer);
	}

	/**
	 * @return value of Encounter
	 */
	public final java.lang.String getEncounter()
	{
		return getEncounter(getContext());
	}

	/**
	 * @param context
	 * @return value of Encounter
	 */
	public final java.lang.String getEncounter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Encounter.toString());
	}

	/**
	 * Set value of Encounter
	 * @param encounter
	 */
	public final void setEncounter(java.lang.String encounter)
	{
		setEncounter(getContext(), encounter);
	}

	/**
	 * Set value of Encounter
	 * @param context
	 * @param encounter
	 */
	public final void setEncounter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String encounter)
	{
		getMendixObject().setValue(context, MemberNames.Encounter.toString(), encounter);
	}

	/**
	 * @return value of UserOrRole
	 */
	public final java.lang.String getUserOrRole()
	{
		return getUserOrRole(getContext());
	}

	/**
	 * @param context
	 * @return value of UserOrRole
	 */
	public final java.lang.String getUserOrRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserOrRole.toString());
	}

	/**
	 * Set value of UserOrRole
	 * @param userorrole
	 */
	public final void setUserOrRole(java.lang.String userorrole)
	{
		setUserOrRole(getContext(), userorrole);
	}

	/**
	 * Set value of UserOrRole
	 * @param context
	 * @param userorrole
	 */
	public final void setUserOrRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userorrole)
	{
		getMendixObject().setValue(context, MemberNames.UserOrRole.toString(), userorrole);
	}

	/**
	 * @return value of Where
	 */
	public final java.lang.String getWhere()
	{
		return getWhere(getContext());
	}

	/**
	 * @param context
	 * @return value of Where
	 */
	public final java.lang.String getWhere(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Where.toString());
	}

	/**
	 * Set value of Where
	 * @param where
	 */
	public final void setWhere(java.lang.String where)
	{
		setWhere(getContext(), where);
	}

	/**
	 * Set value of Where
	 * @param context
	 * @param where
	 */
	public final void setWhere(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String where)
	{
		getMendixObject().setValue(context, MemberNames.Where.toString(), where);
	}

	/**
	 * @return value of ByWhom
	 */
	public final java.lang.String getByWhom()
	{
		return getByWhom(getContext());
	}

	/**
	 * @param context
	 * @return value of ByWhom
	 */
	public final java.lang.String getByWhom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ByWhom.toString());
	}

	/**
	 * Set value of ByWhom
	 * @param bywhom
	 */
	public final void setByWhom(java.lang.String bywhom)
	{
		setByWhom(getContext(), bywhom);
	}

	/**
	 * Set value of ByWhom
	 * @param context
	 * @param bywhom
	 */
	public final void setByWhom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bywhom)
	{
		getMendixObject().setValue(context, MemberNames.ByWhom.toString(), bywhom);
	}

	/**
	 * @return value of Reason
	 */
	public final java.lang.String getReason()
	{
		return getReason(getContext());
	}

	/**
	 * @param context
	 * @return value of Reason
	 */
	public final java.lang.String getReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reason.toString());
	}

	/**
	 * Set value of Reason
	 * @param reason
	 */
	public final void setReason(java.lang.String reason)
	{
		setReason(getContext(), reason);
	}

	/**
	 * Set value of Reason
	 * @param context
	 * @param reason
	 */
	public final void setReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reason)
	{
		getMendixObject().setValue(context, MemberNames.Reason.toString(), reason);
	}

	/**
	 * @return value of Referrals_RecentTests
	 */
	public final emrsystem.proxies.RecentTests getReferrals_RecentTests() throws com.mendix.core.CoreException
	{
		return getReferrals_RecentTests(getContext());
	}

	/**
	 * @param context
	 * @return value of Referrals_RecentTests
	 */
	public final emrsystem.proxies.RecentTests getReferrals_RecentTests(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emrsystem.proxies.RecentTests result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Referrals_RecentTests.toString());
		if (identifier != null)
			result = emrsystem.proxies.RecentTests.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Referrals_RecentTests
	 * @param referrals_recenttests
	 */
	public final void setReferrals_RecentTests(emrsystem.proxies.RecentTests referrals_recenttests)
	{
		setReferrals_RecentTests(getContext(), referrals_recenttests);
	}

	/**
	 * Set value of Referrals_RecentTests
	 * @param context
	 * @param referrals_recenttests
	 */
	public final void setReferrals_RecentTests(com.mendix.systemwideinterfaces.core.IContext context, emrsystem.proxies.RecentTests referrals_recenttests)
	{
		if (referrals_recenttests == null)
			getMendixObject().setValue(context, MemberNames.Referrals_RecentTests.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Referrals_RecentTests.toString(), referrals_recenttests.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return referralsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emrsystem.proxies.Referrals that = (emrsystem.proxies.Referrals) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EMRSystem.Referrals";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
