// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emrsystem.proxies;

public class RiskAndWarning
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject riskAndWarningMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EMRSystem.RiskAndWarning";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MedicationID("MedicationID"),
		RiskAndWarningDescription("RiskAndWarningDescription"),
		RiskAndWarning_Medication("EMRSystem.RiskAndWarning_Medication");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RiskAndWarning(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EMRSystem.RiskAndWarning"));
	}

	protected RiskAndWarning(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject riskAndWarningMendixObject)
	{
		if (riskAndWarningMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EMRSystem.RiskAndWarning", riskAndWarningMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EMRSystem.RiskAndWarning");

		this.riskAndWarningMendixObject = riskAndWarningMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RiskAndWarning.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static emrsystem.proxies.RiskAndWarning initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emrsystem.proxies.RiskAndWarning.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emrsystem.proxies.RiskAndWarning initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emrsystem.proxies.RiskAndWarning(context, mendixObject);
	}

	public static emrsystem.proxies.RiskAndWarning load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emrsystem.proxies.RiskAndWarning.initialize(context, mendixObject);
	}

	public static java.util.List<emrsystem.proxies.RiskAndWarning> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emrsystem.proxies.RiskAndWarning> result = new java.util.ArrayList<emrsystem.proxies.RiskAndWarning>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EMRSystem.RiskAndWarning" + xpathConstraint))
			result.add(emrsystem.proxies.RiskAndWarning.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MedicationID
	 */
	public final java.lang.String getMedicationID()
	{
		return getMedicationID(getContext());
	}

	/**
	 * @param context
	 * @return value of MedicationID
	 */
	public final java.lang.String getMedicationID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MedicationID.toString());
	}

	/**
	 * Set value of MedicationID
	 * @param medicationid
	 */
	public final void setMedicationID(java.lang.String medicationid)
	{
		setMedicationID(getContext(), medicationid);
	}

	/**
	 * Set value of MedicationID
	 * @param context
	 * @param medicationid
	 */
	public final void setMedicationID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String medicationid)
	{
		getMendixObject().setValue(context, MemberNames.MedicationID.toString(), medicationid);
	}

	/**
	 * @return value of RiskAndWarningDescription
	 */
	public final java.lang.String getRiskAndWarningDescription()
	{
		return getRiskAndWarningDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of RiskAndWarningDescription
	 */
	public final java.lang.String getRiskAndWarningDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RiskAndWarningDescription.toString());
	}

	/**
	 * Set value of RiskAndWarningDescription
	 * @param riskandwarningdescription
	 */
	public final void setRiskAndWarningDescription(java.lang.String riskandwarningdescription)
	{
		setRiskAndWarningDescription(getContext(), riskandwarningdescription);
	}

	/**
	 * Set value of RiskAndWarningDescription
	 * @param context
	 * @param riskandwarningdescription
	 */
	public final void setRiskAndWarningDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String riskandwarningdescription)
	{
		getMendixObject().setValue(context, MemberNames.RiskAndWarningDescription.toString(), riskandwarningdescription);
	}

	/**
	 * @return value of RiskAndWarning_Medication
	 */
	public final emrsystem.proxies.CurrentMedication getRiskAndWarning_Medication() throws com.mendix.core.CoreException
	{
		return getRiskAndWarning_Medication(getContext());
	}

	/**
	 * @param context
	 * @return value of RiskAndWarning_Medication
	 */
	public final emrsystem.proxies.CurrentMedication getRiskAndWarning_Medication(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emrsystem.proxies.CurrentMedication result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RiskAndWarning_Medication.toString());
		if (identifier != null)
			result = emrsystem.proxies.CurrentMedication.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RiskAndWarning_Medication
	 * @param riskandwarning_medication
	 */
	public final void setRiskAndWarning_Medication(emrsystem.proxies.CurrentMedication riskandwarning_medication)
	{
		setRiskAndWarning_Medication(getContext(), riskandwarning_medication);
	}

	/**
	 * Set value of RiskAndWarning_Medication
	 * @param context
	 * @param riskandwarning_medication
	 */
	public final void setRiskAndWarning_Medication(com.mendix.systemwideinterfaces.core.IContext context, emrsystem.proxies.CurrentMedication riskandwarning_medication)
	{
		if (riskandwarning_medication == null)
			getMendixObject().setValue(context, MemberNames.RiskAndWarning_Medication.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RiskAndWarning_Medication.toString(), riskandwarning_medication.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return riskAndWarningMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emrsystem.proxies.RiskAndWarning that = (emrsystem.proxies.RiskAndWarning) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EMRSystem.RiskAndWarning";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
